In [1]:
#Import all the dependencies

%matplotlib notebook
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.lines import Line2D
import numpy as np

import sys
import os
sys.path.insert(0, os.path.abspath('Support'))

from math_functions import *
from Obstacle import *

In [2]:
obstacle1 = Rectangle(origin=np.array([10, 20]), width=30, height=5)
print(obstacle1.__init__)

<bound method Rectangle.__init__ of <Obstacle.Rectangle object at 0x000001F2822F3E50>>


In [3]:
boundary_points, goal_distances = [], []
print(boundary_points)

[]


In [4]:
wheel_velocities_range = range(20, 80, 15)
num = len(wheel_velocities_range)
print(wheel_velocities_range)
print(num)

range(20, 80, 15)
4


In [5]:
initial_robot_pos = [30.0, 40.0]
 
robot_path = [initial_robot_pos]
current_robot_pos = initial_robot_pos
print(initial_robot_pos)
print(robot_path)
print(current_robot_pos)

[30.0, 40.0]
[[30.0, 40.0]]
[30.0, 40.0]


In [9]:
a = np.arange(12)
print(a)
b=a #对象复制,a,b地址一样
print(b)
b.shape = 3,4 #a对象的shape也会变化
print (a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
c = a.view()#c的引用地址变化了
print(c)
c.shape = 2,6 #a.shape不变,但是修改c的数据会导致a的数据也会变化
c[0]=999
print(a)
print(c)

[[999 999 999 999]
 [999 999   6   7]
 [  8   9  10  11]]
[[999 999 999 999]
 [999 999   6   7]
 [  8   9  10  11]]
[[999 999 999 999 999 999]
 [  6   7   8   9  10  11]]


In [13]:
a = np.arange(12)
print(a)
b=a #对象复制,a,b地址一样
b.shape = 3,4 #a对象的shape也会变化
print(b)

d = a.copy()  #deep copy
print(d)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
a = np.array([1,2,3,4,5,1,6,1]) 
print (np.where(a == a.min()))
print (np.argmin(a))

(array([0, 5, 7], dtype=int64),)
0


In [18]:
goal_pos = [20.0, 10.0]
print(goal_pos[0])
print(goal_pos[1])

20.0
10.0
