In [32]:
import numpy as np

def get_front_wheel_location(rear_wheel_loc=np.zeros(2), theta=0, length=0):
    
    front_wheel_loc = np.zeros(2)
    #----------------- Add your code here ----------------------
    front_wheel_loc[0] = rear_wheel_loc[0] + length*np.cos(theta)
    front_wheel_loc[1] = rear_wheel_loc[1] + length*np.sin(theta)
        
    #-----------------------------------------------------------
    return front_wheel_loc

In [33]:
rear = [1,1]
front = get_front_wheel_location(rear, np.pi/2, 1)
print(front)
'''front_wheel_loc = np.zeros(2)
print(front_wheel_loc)
front_wheel_loc[0] = 1
print(front_wheel_loc)'''

[1. 2.]


'front_wheel_loc = np.zeros(2)\nprint(front_wheel_loc)\nfront_wheel_loc[0] = 1\nprint(front_wheel_loc)'

In [40]:
def get_bicycle_trajectory(initial_state = np.array([1, 1, 0, 0]), length=1, max_it=100, v=0, phi=0):
    
    dt = 0.05
    states = np.zeros((max_it+1, initial_state.shape[0]))
    states[0,:] = initial_state
    
    
    #----------------- Add your code here ----------------------
    
    #-----------------------------------------------------------
        
    return states

In [41]:
    initial_state = np.array([1, 1, 0, 0])
    length=1
    max_it=10
    v=0
    phi=0
    dt = 0.05
    states = np.zeros((max_it+1, initial_state.shape[0]))
    states[0,:] = initial_state

In [49]:
print(states)
print(initial_state.shape[0])

[[1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
4


In [51]:
max_it = 10
for i in range(1,max_it):
    # Compute next position
    #next_x = x + v_x * dt
    #next_y = y + v_y * dt
    print(i)

1
2
3
4
5
6
7
8
9
